import OpenAI from 'openai';
import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { story, customPrompt, templateContext, llmProvider, llmApiKey } = body;

    if (!story || !story.description) {
      return NextResponse.json({ 
        success: false, 
        error: 'Story data is required to generate a test plan.' 
      }, { status: 400 });
    }

    if (!llmApiKey) {
      return NextResponse.json({ 
        success: false, 
        error: 'API Key is required. Please add it in the Settings panel.' 
      }, { status: 401 });
    }

    let systemInstruction = `You are an expert QA Automation Architect. 
Your job is to read Jira user stories and generate a highly structured, professional Test Plan in raw JSON format.
DO NOT wrap the output in markdown code blocks (e.g., no \\`\`\`json). 
Output raw JSON starting with { and ending with }.`;

    if (templateContext && templateContext.trim() !== "") {
      systemInstruction += `\n\nIMPORTANT FORMATTING RULE:\nYou MUST structure your JSON output to perfectly match the sections and headers found in this reference template:\n"""\n${templateContext}\n"""`;
    } else {
      systemInstruction += `\n\nSince no template was provided, structure your JSON output exactly with these keys: "testPlanId", "title", "objectives", "scope", "testStrategy", "environmentRequirements", and "risks".`;
    }

    if (customPrompt && customPrompt.trim() !== "") {
      systemInstruction += `\n\nADDITIONAL USER CONSTRAINTS:\n${customPrompt}`;
    }

    const userMessage = `Generate a JSON Test Plan for the following Jira Story:\n\nKey: ${story.key}\nSummary: ${story.summary}\nDescription: ${story.description}`;

    let generatedContent = "";

    // --- NEW: Call OpenAI ---
    if (llmProvider === 'openai') {
      const openai = new OpenAI({ apiKey: llmApiKey });
      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [
          { role: "system", content: systemInstruction },
          { role: "user", content: userMessage }
        ],
        temperature: 0.1,
        response_format: { type: "json_object" }
      });
      generatedContent = response.choices[0]?.message?.content || "";
    }

    // 2. Call Groq
    if (llmProvider === 'groq') {
      const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${llmApiKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          model: 'llama-3.3-70b-versatile',
          messages: [
            { role: 'system', content: systemInstruction },
            { role: 'user', content: userMessage }
          ],
          response_format: { type: "json_object" },
          temperature: 0.1 
        })
      });

      const data = await response.json();

      if (!response.ok) {
        console.error("Groq Error Data:", data);
        if (data.error?.code === 'json_validate_failed') {
             throw new Error(`The LLM failed to generate a valid JSON response. Try shortening the prompt or template.`);
        }
        throw new Error(data.error?.message || `Groq API returned status ${response.status}`);
      }

      generatedContent = data.choices?.[0]?.message?.content;
    }

    if (!generatedContent) {
        throw new Error("No content generated by the LLM.");
    }

    let parsedJson;
    try {
      parsedJson = JSON.parse(generatedContent);
    } catch (parseError) {
      console.error("Failed to parse JSON response:", generatedContent);
      return NextResponse.json({ 
        success: false, 
        error: 'The AI returned invalid JSON. Please try again.',
        rawText: generatedContent
      }, { status: 500 });
    }

    return NextResponse.json({ 
        success: true, 
        testPlan: parsedJson 
    });

  } catch (error: any) {
    console.error('Test Plan Generation Error:', error);
    return NextResponse.json({ 
      success: false, 
      error: error.message || 'An unexpected error occurred during test plan generation.' 
    }, { status: 500 });
  }
}
